name: Deploy

on:
  push
#  release:
#    types:
#      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: google-cloud
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: projects/${{ secrets.GOOGLE_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/github
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: Update image
        run: >
          gcloud compute instances update-container discord
          --zone=${{secrets.GOOGLE_CLOUD_ZONE}}
          --container-image=ghcr.io/${{ github.repository }}:latest
          --container-env=GFYCAT_CLIENT_SECRET=${{secrets.GFYCAT_CLIENT_SECRET}}
          --container-env=GFYCAT_CLIENT_ID=${{secrets.GFYCAT_CLIENT_ID}}
          --container-env=DISCORD_TOKEN=${{secrets.DISCORD_TOKEN}}
          --container-env=SENTRY_DSN=${{secrets.SENTRY_DSN}}
          --container-env=ARCHIVE_MODE=cloud
          --container-env=CLOUD_BUCKET_NAME=${{vars.CLOUD_BUCKET_NAME}}
          --container-env=CLOUD_PROJECT_ID=${{secrets.CLOUD_PROJECT_ID}}
          --container-env=ENVIRONMENT=${{vars.ENVIRONMENT}}